[2024-12-03T19:09:58.351+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T19:09:58.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:09:30.926688+00:00 [queued]>
[2024-12-03T19:09:58.377+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:09:30.926688+00:00 [queued]>
[2024-12-03T19:09:58.378+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T19:09:58.386+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-03 19:09:30.926688+00:00
[2024-12-03T19:09:58.401+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2760) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T19:09:58.403+0000] {standard_task_runner.py:63} INFO - Started process 2762 to run task
[2024-12-03T19:09:58.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-12-03T19:09:30.926688+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpvne4uxin']
[2024-12-03T19:09:58.407+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask dbt_test
[2024-12-03T19:09:58.443+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:09:30.926688+00:00 [running]> on host 2adeb2e19af7
[2024-12-03T19:09:58.502+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T19:09:30.926688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T19:09:30.926688+00:00'
[2024-12-03T19:09:58.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T19:09:58.506+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-03T19:09:58.510+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-03T19:09:58.533+0000] {subprocess.py:86} INFO - Output:
[2024-12-03T19:10:03.273+0000] {subprocess.py:93} INFO - [0m19:10:03  Running with dbt=1.8.7
[2024-12-03T19:10:07.017+0000] {subprocess.py:93} INFO - [0m19:10:07  Registered adapter: snowflake=1.8.4
[2024-12-03T19:10:07.481+0000] {subprocess.py:93} INFO - [0m19:10:07  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-03T19:10:07.493+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-03T19:10:07.499+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-03T19:10:07.962+0000] {subprocess.py:93} INFO - [0m19:10:07  Found 1 snapshot, 3 models, 2 sources, 459 macros
[2024-12-03T19:10:07.973+0000] {subprocess.py:93} INFO - [0m19:10:07
[2024-12-03T19:10:07.977+0000] {subprocess.py:93} INFO - [0m19:10:07  Nothing to do. Try checking your model configs and model specification args
[2024-12-03T19:10:09.707+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-03T19:10:09.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T19:10:09.837+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-12-03T19:09:30.926688+00:00, execution_date=20241203T190930, start_date=20241203T190958, end_date=20241203T191009
[2024-12-03T19:10:09.968+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T19:10:10.034+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-03T19:10:10.045+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
