[2024-12-03T19:28:53.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T19:28:53.663+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:27:48.904833+00:00 [queued]>
[2024-12-03T19:28:53.672+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:27:48.904833+00:00 [queued]>
[2024-12-03T19:28:53.673+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T19:28:53.685+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-03 19:27:48.904833+00:00
[2024-12-03T19:28:53.700+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3086) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T19:28:53.703+0000] {standard_task_runner.py:63} INFO - Started process 3088 to run task
[2024-12-03T19:28:53.703+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-12-03T19:27:48.904833+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp_fsyot1o']
[2024-12-03T19:28:53.706+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask dbt_test
[2024-12-03T19:28:53.750+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-03T19:27:48.904833+00:00 [running]> on host 2adeb2e19af7
[2024-12-03T19:28:53.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T19:27:48.904833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T19:27:48.904833+00:00'
[2024-12-03T19:28:53.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T19:28:53.827+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-03T19:28:53.828+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-03T19:28:53.843+0000] {subprocess.py:86} INFO - Output:
[2024-12-03T19:29:01.206+0000] {subprocess.py:93} INFO - [0m19:29:01  Running with dbt=1.8.7
[2024-12-03T19:29:03.292+0000] {subprocess.py:93} INFO - [0m19:29:03  Registered adapter: snowflake=1.8.4
[2024-12-03T19:29:03.883+0000] {subprocess.py:93} INFO - [0m19:29:03  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-03T19:29:03.887+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-03T19:29:03.893+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-03T19:29:04.446+0000] {subprocess.py:93} INFO - [0m19:29:04  Found 2 snapshots, 3 models, 2 sources, 459 macros
[2024-12-03T19:29:04.458+0000] {subprocess.py:93} INFO - [0m19:29:04
[2024-12-03T19:29:04.506+0000] {subprocess.py:93} INFO - [0m19:29:04  Nothing to do. Try checking your model configs and model specification args
[2024-12-03T19:29:06.000+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-03T19:29:06.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T19:29:06.445+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-12-03T19:27:48.904833+00:00, execution_date=20241203T192748, start_date=20241203T192853, end_date=20241203T192906
[2024-12-03T19:29:06.624+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T19:29:06.762+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-03T19:29:06.771+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
