[2024-12-04T17:59:00.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T17:59:00.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-04T17:58:23.613275+00:00 [queued]>
[2024-12-04T17:59:00.731+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-04T17:58:23.613275+00:00 [queued]>
[2024-12-04T17:59:00.732+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-04T17:59:00.739+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-04 17:58:23.613275+00:00
[2024-12-04T17:59:00.749+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1059) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T17:59:00.751+0000] {standard_task_runner.py:63} INFO - Started process 1061 to run task
[2024-12-04T17:59:00.751+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-12-04T17:58:23.613275+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp9iv4hhx3']
[2024-12-04T17:59:00.754+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask dbt_test
[2024-12-04T17:59:00.787+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-04T17:58:23.613275+00:00 [running]> on host 2adeb2e19af7
[2024-12-04T17:59:00.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T17:58:23.613275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T17:58:23.613275+00:00'
[2024-12-04T17:59:00.847+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T17:59:00.848+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-04T17:59:00.850+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-04T17:59:00.861+0000] {subprocess.py:86} INFO - Output:
[2024-12-04T17:59:02.475+0000] {subprocess.py:93} INFO - [0m17:59:02  Running with dbt=1.8.7
[2024-12-04T17:59:03.194+0000] {subprocess.py:93} INFO - [0m17:59:03  Registered adapter: snowflake=1.8.4
[2024-12-04T17:59:03.431+0000] {subprocess.py:93} INFO - [0m17:59:03  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-04T17:59:03.432+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-04T17:59:03.435+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-04T17:59:03.643+0000] {subprocess.py:93} INFO - [0m17:59:03  Found 2 snapshots, 3 models, 2 sources, 459 macros
[2024-12-04T17:59:03.649+0000] {subprocess.py:93} INFO - [0m17:59:03
[2024-12-04T17:59:03.650+0000] {subprocess.py:93} INFO - [0m17:59:03  Nothing to do. Try checking your model configs and model specification args
[2024-12-04T17:59:04.451+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-04T17:59:04.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T17:59:04.494+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-12-04T17:58:23.613275+00:00, execution_date=20241204T175823, start_date=20241204T175900, end_date=20241204T175904
[2024-12-04T17:59:04.541+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-04T17:59:04.586+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T17:59:04.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
